const products = [
    {
        id: 1,
        brand: "Harley Davidson",
        model: "Softail Deluxe FLSTN",
        style: "Cruiser",
        year: 2011,
        condition: "Usada",
        displacement: 103,
        displacementUnit: "ci",
        power: 72,
        kilometers: 55000,
        price: 29900,
        rating: 1,
        image: "/Product/img_softail_deluxe_flstn.jpg",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 2,
        brand: "Harley Davidson",
        model: "Sportster Forty Eight",
        style: "Cruiser",
        year: 2013,
        condition: "Usada",
        displacement: 1200,
        displacementUnit: "cc",
        power: 66,
        kilometers: 20000,
        price: 19900,
        rating: 5,
        image: "/Product/img_sportster_forty_eight.png",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 3,
        brand: "Ducati",
        model: "Multistrada V4",
        style: "Enduro",
        year: 2024,
        condition: "Nueva",
        displacement: 1158,
        displacementUnit: "cc",
        power: 170,
        kilometers: 0,
        price: 40900,
        rating: 4,
        image: "/Product/img_multistrada_v4.png",
        logo: "/Logo/logo_ducati.png"
    },
    {
        id: 4,
        brand: "KTM",
        model: "1190 Adventure R",
        style: "Enduro",
        year: 2015,
        condition: "Usada",
        displacement: 1190,
        displacementUnit: "cc",
        power: 150,
        kilometers: 25000,
        price: 16000,
        rating: 4,
        image: "/Product/img_1190_adventure_r.jpeg",
        logo: "/Logo/logo_ktm.png"
    },
    {
        id: 5,
        brand: "Kawasaki",
        model: "ZX-10R",
        style: "Sport",
        year: 2024,
        condition: "Nueva",
        displacement: 998,
        displacementUnit: "cc",
        power: 200,
        kilometers: 0,
        price: 34990,
        rating: 2,
        image: "/Product/img_zx10r.png",
        logo: "/Logo/logo_kawasaki.svg"
    },
    {
        id: 6,
        brand: "Husqvarna",
        model: "Svartpilen 701",
        style: "Street",
        year: 2020,
        condition: "Usada",
        displacement: 692,
        displacementUnit: "cc",
        power: 75,
        kilometers: 2500,
        price: 10900,
        rating: 1,
        image: "/Product/img_svartpilen_701.jpeg",
        logo: "/Logo/logo_husqvarna.png"
    },
    {
        id: 7,
        brand: "BMW",
        model: "M 1000R",
        style: "Sport",
        year: 2024,
        condition: "Nueva",
        displacement: 999,
        displacementUnit: "cc",
        power: 210,
        kilometers: 0,
        price: 79990,
        rating: 4,
        image: "/Product/img_m1000r.jpeg",
        logo: "/Logo/logo_bmw.png"
    },
    {
        id: 8,
        brand: "Yamaha",
        model: "MT-09",
        style: "Street",
        year: 2024,
        condition: "Nueva",
        displacement: 890,
        displacementUnit: "cc",
        power: 120,
        kilometers: 0,
        price: 18900,
        rating: 5,
        image: "/Product/img_mt09.avif",
        logo: "/Logo/logo_yamaha.png"
    },
    {
        id: 9,
        brand: "Triumph",
        model: "Scrambler 1200 X",
        style: "Enduro",
        year: 2024,
        condition: "Nueva",
        displacement: 1200,
        displacementUnit: "cc",
        power: 90,
        kilometers: 0,
        price: 38900,
        rating: 5,
        image: "/Product/img_scrambler1200x.avif",
        logo: "/Logo/logo_triumph.svg"
    },
    {
        id: 10,
        brand: "Harley Davidson",
        model: "Road Glide CVO",
        style: "Cruiser",
        year: 2020,
        condition: "Nueva",
        displacement: 117,
        displacementUnit: "ci",
        power: 80,
        kilometers: 0,
        price: 69900,
        rating: 2,
        image: "/Product/img_road_glide_cvo.webp",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 11,
        brand: "Harley Davidson",
        model: "Sportster S",
        style: "Street",
        year: 2024,
        condition: "Nueva",
        displacement: 76,
        displacementUnit: "ci",
        power: 120,
        kilometers: 0,
        price: 39900,
        rating: 4,
        image: "/Product/img_sportster_s.jpeg",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 12,
        brand: "Ducati",
        model: "Hypermotard 950 SP",
        style: "Enduro",
        year: 2018,
        condition: "Usada",
        displacement: 950,
        displacementUnit: "cc",
        power: 115,
        kilometers: 5850,
        price: 14900,
        rating: 2,
        image: "/Product/img_hypermotard_950_sp.jpeg",
        logo: "/Logo/logo_ducati.png"
    },
    {
        id: 13,
        brand: "Ducati",
        model: "Scrambler 1100 Tribute",
        style: "Street",
        year: 2018,
        condition: "Usada",
        displacement: 1100,
        displacementUnit: "cc",
        power: 85,
        kilometers: 10000,
        price: 18900,
        rating: 3,
        image: "/Product/img_scrambler_1100_tribute.jpeg",
        logo: "/Logo/logo_ducati.png"
    },
    {
        id: 14,
        brand: "Indian",
        model: "Chief Classic",
        style: "Cruiser",
        year: 2024,
        condition: "Nueva",
        displacement: 110,
        displacementUnit: "ci",
        power: 80,
        kilometers: 0,
        price: 49900,
        rating: 3,
        image: "/Product/img_chief_classic.jpeg",
        logo: "/Logo/logo_indian.svg"
    },
    {
        id: 15,
        brand: "Yamaha",
        model: "YZ125",
        style: "Cross",
        year: 2024,
        condition: "Nueva",
        displacement: 125,
        displacementUnit: "cc",
        power: 35,
        kilometers: 0,
        price: 10850,
        rating: 5,
        image: "/Product/img_yz125.webp",
        logo: "/Logo/logo_yamaha.png"
    },
    {
        id: 16,
        brand: "Husqvarna",
        model: "Norden 901",
        style: "Enduro",
        year: 2022,
        condition: "Usada",
        displacement: 901,
        displacementUnit: "cc",
        power: 105,
        kilometers: 5000,
        price: 15990,
        rating: 1,
        image: "/Product/img_norden_901.jpeg",
        logo: "/Logo/logo_husqvarna.png"
    },
    {
        id: 17,
        brand: "Husqvarna",
        model: "Enduro 701",
        style: "Enduro",
        year: 2024,
        condition: "Nueva",
        displacement: 701,
        displacementUnit: "cc",
        power: 75,
        kilometers: 0,
        price: 10990,
        rating: 4,
        image: "/Product/img_enduro_701.webp",
        logo: "/Logo/logo_husqvarna.png"
    },
    {
        id: 18,
        brand: "Husqvarna",
        model: "Viptilen 401",
        style: "Street",
        year: 2018,
        condition: "Usada",
        displacement: 401,
        displacementUnit: "cc",
        power: 45,
        kilometers: 8500,
        price: 6900,
        rating: 4,
        image: "/Product/img_viptilen_401.avif",
        logo: "/Logo/logo_husqvarna.png"
    },
    {
        id: 19,
        brand: "Yamaha",
        model: "XSR900",
        style: "Street",
        year: 2020,
        condition: "Usada",
        displacement: 900,
        displacementUnit: "cc",
        power: 115,
        kilometers: 500,
        price: 20900,
        rating: 5,
        image: "/Product/img_xsr900.avif",
        logo: "/Logo/logo_yamaha.png"
    },
    {
        id: 20,
        brand: "Yamaha",
        model: "Jog",
        style: "Scooter",
        year: 1990,
        condition: "Usada",
        displacement: 45,
        displacementUnit: "cc",
        power: 4.5,
        kilometers: 25000,
        price: 1090,
        rating: 5,
        image: "/Product/img_jog.webp",
        logo: "/Logo/logo_yamaha.png"
    },
    {
        id: 22,
        brand: "Harley Davidson",
        model: "Tri Glide Ultra",
        style: "Cruiser",
        year: 2024,
        condition: "Nueva",
        displacement: 114,
        displacementUnit: "ci",
        power: 90,
        kilometers: 0,
        price: 59900,
        rating: 2,
        image: "/Product/img_tri_glide_ultra.webp",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 23,
        brand: "Ducati",
        model: "Panigale V4",
        style: "Sport",
        year: 2024,
        condition: "Nueva",
        displacement: 1100,
        displacementUnit: "cc",
        power: 210,
        kilometers: 0,
        price: 49900,
        rating: 4,
        image: "/Product/img_panigale_v4.webp",
        logo: "/Logo/logo_ducati.png"
    },
    {
        id: 24,
        brand: "Ducati",
        model: "DesertX",
        style: "Enduro",
        year: 2022,
        condition: "Usada",
        displacement: 937,
        displacementUnit: "cc",
        power: 110,
        kilometers: 10000,
        price: 27900,
        rating: 4,
        image: "/Product/img_desertx.webp",
        logo: "/Logo/logo_ducati.png"
    },
    {
        id: 25,
        brand: "Ducati",
        model: "XDiavel",
        style: "Street",
        year: 2018,
        condition: "Usada",
        displacement: 1262,
        displacementUnit: "cc",
        power: 150,
        kilometers: 25000,
        price: 25900,
        rating: 5,
        image: "/Product/img_xdiavel.png",
        logo: "/Logo/logo_ducati.png"
    },
    {
        id: 26,
        brand: "Harley Davidson",
        model: "Fat Boy",
        style: "Cruiser",
        year: 2003,
        condition: "Usada",
        displacement: 1450,
        displacementUnit: "cc",
        power: 65,
        kilometers: 55000,
        price: 20900,
        rating: 5,
        image: "/Product/img_fat_boy.jpeg",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 27,
        brand: "Harley Davidson",
        model: "Pan America",
        style: "Enduro",
        year: 2024,
        condition: "Nueva",
        displacement: 1250,
        displacementUnit: "cc",
        power: 150,
        kilometers: 0,
        price: 32900,
        rating: 5,
        image: "/Product/img_pan_america.png",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 28,
        brand: "BMW",
        model: "R 1200 GS Adventure",
        style: "Enduro",
        year: 2024,
        condition: "Nueva",
        displacement: 1200,
        displacementUnit: "cc",
        power: 125,
        kilometers: 0,
        price: 49900,
        rating: 5,
        image: "/Product/img_r1200_gs_adventure.jpeg",
        logo: "/Logo/logo_bmw.png"
    },
    {
        id: 29,
        brand: "BMW",
        model: "S1000 RR",
        style: "Sport",
        year: 2020,
        condition: "Usada",
        displacement: 1000,
        displacementUnit: "cc",
        power: 205,
        kilometers: 15000,
        price: 29900,
        rating: 1,
        image: "/Product/img_s1000_rr.avif",
        logo: "/Logo/logo_bmw.png"
    },
    {
        id: 30,
        brand: "BMW",
        model: "CE 04",
        style: "Scooter",
        year: 2024,
        condition: "Nueva",
        displacement: 0,
        displacementUnit: "-",
        power: 20,
        kilometers: 0,
        price: 19900,
        rating: 3,
        image: "/Product/img_ce_04.webp",
        logo: "/Logo/logo_bmw.png"
    },
    {
        id: 31,
        brand: "Husqvarna",
        model: "FC 450",
        style: "Cross",
        year: 2024,
        condition: "Nueva",
        displacement: 450,
        displacementUnit: "cc",
        power: 60,
        kilometers: 0,
        price: 17900,
        rating: 5,
        image: "/Product/img_fc_450.png",
        logo: "/Logo/logo_husqvarna.png"
    },
    {
        id: 32,
        brand: "Husqvarna",
        model: "Vitpilen 701",
        style: "Street",
        year: 2018,
        condition: "Usada",
        displacement: 692,
        displacementUnit: "cc",
        power: 75,
        kilometers: 15000,
        price: 12900,
        rating: 4,
        image: "/Product/img_vitpilen_701.jpeg",
        logo: "/Logo/logo_husqvarna.png"
    },
    {
        id: 33,
        brand: "Kawasaki",
        model: "Z900 RS",
        style: "Street",
        year: 2020,
        condition: "Usada",
        displacement: 900,
        displacementUnit: "cc",
        power: 110,
        kilometers: 12500,
        price: 18900,
        rating: 4,
        image: "/Product/img_z900_rs.png",
        logo: "/Logo/logo_kawasaki.svg"
    },
    {
        id: 34,
        brand: "Kawasaki",
        model: "KX450",
        style: "Cross",
        year: 2022,
        condition: "Usada",
        displacement: 450,
        displacementUnit: "cc",
        power: 55,
        kilometers: 1500,
        price: 12900,
        rating: 3,
        image: "/Product/img_kx450.png",
        logo: "/Logo/logo_kawasaki.svg"
    },
    {
        id: 35,
        brand: "Kawasaki",
        model: "ZX6-R",
        style: "Sport",
        year: 2010,
        condition: "Usada",
        displacement: 600,
        displacementUnit: "cc",
        power: 130,
        kilometers: 1500,
        price: 10900,
        rating: 2,
        image: "/Product/img_zx6r.jpeg",
        logo: "/Logo/logo_kawasaki.svg"
    },
    {
        id: 36,
        brand: "KTM",
        model: "1290 Super Adventure R",
        style: "Enduro",
        year: 2024,
        condition: "Nueva",
        displacement: 1290,
        displacementUnit: "cc",
        power: 160,
        kilometers: 0,
        price: 40900,
        rating: 5,
        image: "/Product/img_1290_super_adventure_r.jpeg",
        logo: "/Logo/logo_ktm.png"
    },
    {
        id: 37,
        brand: "KTM",
        model: "1290 Super Duke R",
        style: "Street",
        year: 2024,
        condition: "Nueva",
        displacement: 1290,
        displacementUnit: "cc",
        power: 180,
        kilometers: 0,
        price: 30900,
        rating: 5,
        image: "/Product/img_1290_super_duke_r.png",
        logo: "/Logo/logo_ktm.png"
    },
    {
        id: 38,
        brand: "Indian",
        model: "Challenger Elite",
        style: "Cruiser",
        year: 2022,
        condition: "Nueva",
        displacement: 108,
        displacementUnit: "ci",
        power: 120,
        kilometers: 0,
        price: 50900,
        rating: 2,
        image: "/Product/img_challenger_elite.png",
        logo: "/Logo/logo_indian.svg"
    },
    {
        id: 39,
        brand: "Indian",
        model: "FTR Rally",
        style: "Street",
        year: 2022,
        condition: "Nueva",
        displacement: 75,
        displacementUnit: "ci",
        power: 120,
        kilometers: 0,
        price: 35900,
        rating: 3,
        image: "/Product/img_ftr_rally.jpeg",
        logo: "/Logo/logo_indian.svg"
    },
    {
        id: 40,
        brand: "Triumph",
        model: "Rocket 3 GT",
        style: "Street",
        year: 2022,
        condition: "Usada",
        displacement: 2500,
        displacementUnit: "cc",
        power: 165,
        kilometers: 16500,
        price: 35900,
        rating: 3,
        image: "/Product/img_rocket_3_gt.png",
        logo: "/Logo/logo_triumph.svg"
    },
    {
        id: 41,
        brand: "Triumph",
        model: "Tiger 1200 Rally Pro",
        style: "Enduro",
        year: 2024,
        condition: "Nueva",
        displacement: 1200,
        displacementUnit: "cc",
        power: 105,
        kilometers: 0,
        price: 29900,
        rating: 4,
        image: "/Product/img_tiger_1200_rally_pro.avif",
        logo: "/Logo/logo_triumph.svg"
    },
    {
        id: 42,
        brand: "Triumph",
        model: "Thruxton RS",
        style: "Street",
        year: 2020,
        condition: "Usada",
        displacement: 1200,
        displacementUnit: "cc",
        power: 100,
        kilometers: 900,
        price: 29900,
        rating: 4,
        image: "/Product/img_thruxton_rs.avif",
        logo: "/Logo/logo_triumph.svg"
    },
    {
        id: 43,
        brand: "Ducati",
        model: "Monster 1100 EVO",
        style: "Street",
        year: 2020,
        condition: "Usada",
        displacement: 1100,
        displacementUnit: "cc",
        power: 100,
        kilometers: 40000,
        price: 12900,
        rating: 5,
        image: "/Product/img_monster_1100_evo.webp",
        logo: "/Logo/logo_ducati.png"
    },
    {
        id: 44,
        brand: "Indian",
        model: "Scout Bobber",
        style: "Cruiser",
        year: 2020,
        condition: "Usada",
        displacement: 70,
        displacementUnit: "ci",
        power: 100,
        kilometers: 8000,
        price: 22900,
        rating: 4,
        image: "/Product/img_scout.jpeg",
        logo: "/Logo/logo_indian.svg"
    },
    {
        id: 45,
        brand: "KTM",
        model: "125 SX",
        style: "Cross",
        year: 2024,
        condition: "Nueva",
        displacement: 125,
        displacementUnit: "cc",
        power: 30,
        kilometers: 0,
        price: 10900,
        rating: 4,
        image: "/Product/img_sx_125.png",
        logo: "/Logo/logo_ktm.png"
    },
    {
        id: 46,
        brand: "KTM",
        model: "RC 200",
        style: "Sport",
        year: 2024,
        condition: "Nueva",
        displacement: 200,
        displacementUnit: "cc",
        power: 25,
        kilometers: 0,
        price: 6900,
        rating: 2,
        image: "/Product/img_rc_200.png",
        logo: "/Logo/logo_ktm.png"
    },
    {
        id: 47,
        brand: "Triumph",
        model: "Bonneville T120",
        style: "Street",
        year: 2019,
        condition: "Usada",
        displacement: 1200,
        displacementUnit: "cc",
        power: 80,
        kilometers: 8500,
        price: 26900,
        rating: 3,
        image: "/Product/img_bonneville_t120.webp",
        logo: "/Logo/logo_triumph.svg"
    },
    {
        id: 48,
        brand: "Harley Davidson",
        model: "Road King Classic",
        style: "Cruiser",
        year: 2015,
        condition: "Usada",
        displacement: 103,
        displacementUnit: "ci",
        power: 72,
        kilometers: 50000,
        price: 34900,
        rating: 1,
        image: "/Product/img_road_king_classic.jpeg",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 49,
        brand: "Harley Davidson",
        model: "Sportster Seventy Two",
        style: "Cruiser",
        year: 2018,
        condition: "Usada",
        displacement: 1200,
        displacementUnit: "cc",
        power: 55,
        kilometers: 7500,
        price: 20900,
        rating: 2,
        image: "/Product/img_sportster_seventy_two.jpeg",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 50,
        brand: "Honda",
        model: "CRF 1000 Africa Twin",
        style: "Enduro",
        year: 2020,
        condition: "Usada",
        displacement: 1000,
        displacementUnit: "cc",
        power: 100,
        kilometers: 7500,
        price: 26900,
        rating: 1,
        image: "/Product/img_crf1000_africa_twin.jpeg",
        logo: "/Logo/logo_honda.svg"
    },
    {
        id: 51,
        brand: "Honda",
        model: "CRF450",
        style: "Cross",
        year: 2024,
        condition: "Nueva",
        displacement: 450,
        displacementUnit: "cc",
        power: 52.5,
        kilometers: 0,
        price: 16900,
        rating: 3,
        image: "/Product/img_crf450.webp",
        logo: "/Logo/logo_honda.svg"
    },
    {
        id: 52,
        brand: "Honda",
        model: "CB650R",
        style: "Street",
        year: 2022,
        condition: "Usada",
        displacement: 650,
        displacementUnit: "cc",
        power: 80,
        kilometers: 5500,
        price: 17900,
        rating: 5,
        image: "/Product/img_cb650r.avif",
        logo: "/Logo/logo_honda.svg"
    },
    {
        id: 53,
        brand: "Honda",
        model: "CBX750",
        style: "Street",
        year: 1990,
        condition: "Usada",
        displacement: 750,
        displacementUnit: "cc",
        power: 95,
        kilometers: 50000,
        price: 7500,
        rating: 4,
        image: "/Product/img_cbx750.webp",
        logo: "/Logo/logo_honda.svg"
    },
    {
        id: 54,
        brand: "Honda",
        model: "CBR1000RR",
        style: "Sport",
        year: 2020,
        condition: "Nueva",
        displacement: 1000,
        displacementUnit: "cc",
        power: 215,
        kilometers: 0,
        price: 26900,
        rating: 4,
        image: "/Product/img_cbr1000rr.avif",
        logo: "/Logo/logo_honda.svg"
    },
    {
        id: 55,
        brand: "Harley Davidson",
        model: "Street Glide CVO",
        style: "Cruiser",
        year: 2020,
        condition: "Nueva",
        displacement: 117,
        displacementUnit: "ci",
        power: 115,
        kilometers: 0,
        price: 68900,
        rating: 2,
        image: "/Product/img_cvo_street_glide.png",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 56,
        brand: "Harley Davidson",
        model: "Sportster 883 Iron",
        style: "Street",
        year: 2015,
        condition: "Usada",
        displacement: 883,
        displacementUnit: "cc",
        power: 65,
        kilometers: 42500,
        price: 14900,
        rating: 2,
        image: "/Product/img_sportster_iron_883.jpeg",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 57,
        brand: "Harley Davidson",
        model: "Electra Glide Ultra Classic",
        style: "Cruiser",
        year: 2018,
        condition: "Usada",
        displacement: 107,
        displacementUnit: "ci",
        power: 85,
        kilometers: 20500,
        price: 34900,
        rating: 2,
        image: "/Product/img_ultra_classic.png",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 58,
        brand: "Harley Davidson",
        model: "Sportster XL1200R Roadster",
        style: "Street",
        year: 2016,
        condition: "Usada",
        displacement: 1200,
        displacementUnit: "cc",
        power: 75,
        kilometers: 25000,
        price: 18900,
        rating: 5,
        image: "/Product/img_xl1200_sportster_roadster.jpeg",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 59,
        brand: "Honda",
        model: "Gold Wing",
        style: "Cruiser",
        year: 2018,
        condition: "Usada",
        displacement: 1800,
        displacementUnit: "cc",
        power: 125,
        kilometers: 5000,
        price: 26900,
        rating: 2,
        image: "/Product/img_gold_wing.avif",
        logo: "/Logo/logo_honda.svg"
    },
    {
        id: 60,
        brand: "BMW",
        model: "R NineT",
        style: "Street",
        year: 2024,
        condition: "Nueva",
        displacement: 1200,
        displacementUnit: "cc",
        power: 115,
        kilometers: 0,
        price: 34900,
        rating: 4,
        image: "/Product/img_r_ninet.avif",
        logo: "/Logo/logo_bmw.png"
    },
    {
        id: 61,
        brand: "Harley Davidson",
        model: "Softail Street Bob",
        style: "Street",
        year: 2018,
        condition: "Usada",
        displacement: 107,
        displacementUnit: "ci",
        power: 75,
        kilometers: 0,
        price: 22900,
        rating: 3,
        image: "/Product/img_softail_street_bob.png",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 62,
        brand: "Harley Davidson",
        model: "Dyna Fat Bob",
        style: "Street",
        year: 2015,
        condition: "Usada",
        displacement: 103,
        displacementUnit: "ci",
        power: 75,
        kilometers: 0,
        price: 20900,
        rating: 4,
        image: "/Product/img_dyna_fat_bob.jpeg",
        logo: "/Logo/logo_harley_davidson.svg"
    },
    {
        id: 63,
        brand: "Harley Davidson",
        model: "Softail Heritage Classic",
        style: "Cruiser",
        year: 2015,
        condition: "Usada",
        displacement: 103,
        displacementUnit: "ci",
        power: 75,
        kilometers: 0,
        price: 21900,
        rating: 3,
        image: "/Product/img_softail_heritage_classic.jpeg",
        logo: "/Logo/logo_harley_davidson.svg"
    }
]

function getProducts() {
    return new Promise( (resolve, reject) => {
        setTimeout(() => {
            resolve(products)
        }, 1000)
    })
}

// export function getProductById(id) {
//     return new Promise((resolve, reject) => {
//         setTimeout(() => {
//             const product = products.find(product => product.id === id)
//             if (product) {
//                 resolve(product)
//             } else {
//                 reject(new Error(`Product with id ${id} not found`))
//             }
//         }, 1000)
//     })
// }

export default getProducts