const products = [
    {
        id: 1,
        marca: "Harley Davidson",
        modelo: "Softail Deluxe FLSTN",
        estilo: "Cruiser",
        anio: 2011,
        condicion: "Usada",
        cilindrada: 103,
        cilindradaMedida: "ci",
        potencia: 72,
        kilometraje: 55000,
        precio: 29900,
        rating: 1,
        imagen: "/product/img_softail_deluxe_flstn.jpg",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 2,
        marca: "Harley Davidson",
        modelo: "Sportster Forty Eight",
        estilo: "Cruiser",
        anio: 2013,
        condicion: "Usada",
        cilindrada: 1200,
        cilindradaMedida: "cc",
        potencia: 66,
        kilometraje: 20000,
        precio: 19900,
        rating: 5,
        imagen: "/product/img_sportster_forty_eight.png",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 3,
        marca: "Ducati",
        modelo: "Multistrada V4",
        estilo: "Enduro",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 1158,
        cilindradaMedida: "cc",
        potencia: 170,
        kilometraje: 0,
        precio: 40900,
        rating: 4,
        imagen: "/product/img_multistrada_v4.png",
        logo: "/logo/logo_ducati.png"
    },
    {
        id: 4,
        marca: "KTM",
        modelo: "1190 Adventure R",
        estilo: "Enduro",
        anio: 2015,
        condicion: "Usada",
        cilindrada: 1190,
        cilindradaMedida: "cc",
        potencia: 150,
        kilometraje: 25000,
        precio: 16000,
        rating: 4,
        imagen: "/product/img_1190_adventure_r.jpeg",
        logo: "/logo/logo_ktm.png"
    },
    {
        id: 5,
        marca: "Kawasaki",
        modelo: "ZX-10R",
        estilo: "Sport",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 998,
        cilindradaMedida: "cc",
        potencia: 200,
        kilometraje: 0,
        precio: 34990,
        rating: 2,
        imagen: "/product/img_zx10r.png",
        logo: "/logo/logo_kawasaki.svg"
    },
    {
        id: 6,
        marca: "Husqvarna",
        modelo: "Svartpilen 701",
        estilo: "Street",
        anio: 2020,
        condicion: "Usada",
        cilindrada: 692,
        cilindradaMedida: "cc",
        potencia: 75,
        kilometraje: 2500,
        precio: 10900,
        rating: 1,
        imagen: "/product/img_svartpilen_701.jpeg",
        logo: "/logo/logo_husqvarna.png"
    },
    {
        id: 7,
        marca: "BMW",
        modelo: "M 1000R",
        estilo: "Sport",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 999,
        cilindradaMedida: "cc",
        potencia: 210,
        kilometraje: 0,
        precio: 79990,
        rating: 4,
        imagen: "/product/img_m1000r.jpeg",
        logo: "/logo/logo_bmw.png"
    },
    {
        id: 8,
        marca: "Yamaha",
        modelo: "MT-09",
        estilo: "Street",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 890,
        cilindradaMedida: "cc",
        potencia: 120,
        kilometraje: 0,
        precio: 18900,
        rating: 5,
        imagen: "/product/img_mt09.avif",
        logo: "/logo/logo_yamaha.png"
    },
    {
        id: 9,
        marca: "Triumph",
        modelo: "Scrambler 1200 X",
        estilo: "Enduro",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 1200,
        cilindradaMedida: "cc",
        potencia: 90,
        kilometraje: 0,
        precio: 38900,
        rating: 5,
        imagen: "/product/img_scrambler1200x.avif",
        logo: "/logo/logo_triumph.svg"
    },
    {
        id: 10,
        marca: "Harley Davidson",
        modelo: "Road Glide CVO",
        estilo: "Cruiser",
        anio: 2020,
        condicion: "Nueva",
        cilindrada: 117,
        cilindradaMedida: "ci",
        potencia: 80,
        kilometraje: 0,
        precio: 69900,
        rating: 2,
        imagen: "/product/img_road_glide_cvo.webp",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 11,
        marca: "Harley Davidson",
        modelo: "Sportster S",
        estilo: "Street",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 76,
        cilindradaMedida: "ci",
        potencia: 120,
        kilometraje: 0,
        precio: 39900,
        rating: 4,
        imagen: "/product/img_sportster_s.jpeg",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 12,
        marca: "Ducati",
        modelo: "Hypermotard 950 SP",
        estilo: "Enduro",
        anio: 2018,
        condicion: "Usada",
        cilindrada: 950,
        cilindradaMedida: "cc",
        potencia: 115,
        kilometraje: 5850,
        precio: 14900,
        rating: 2,
        imagen: "/product/img_hypermotard_950_sp.jpeg",
        logo: "/logo/logo_ducati.png"
    },
    {
        id: 13,
        marca: "Ducati",
        modelo: "Scrambler 1100 Tribute",
        estilo: "Street",
        anio: 2018,
        condicion: "Usada",
        cilindrada: 1100,
        cilindradaMedida: "cc",
        potencia: 85,
        kilometraje: 10000,
        precio: 18900,
        rating: 3,
        imagen: "/product/img_scrambler_1100_tribute.jpeg",
        logo: "/logo/logo_ducati.png"
    },
    {
        id: 14,
        marca: "Indian",
        modelo: "Chief Classic",
        estilo: "Cruiser",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 110,
        cilindradaMedida: "ci",
        potencia: 80,
        kilometraje: 0,
        precio: 49900,
        rating: 3,
        imagen: "/product/img_chief_classic.jpeg",
        logo: "/logo/logo_indian.svg"
    },
    {
        id: 15,
        marca: "Yamaha",
        modelo: "YZ125",
        estilo: "Cross",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 125,
        cilindradaMedida: "cc",
        potencia: 35,
        kilometraje: 0,
        precio: 10850,
        rating: 5,
        imagen: "/product/img_yz125.webp",
        logo: "/logo/logo_yamaha.png"
    },
    {
        id: 16,
        marca: "Husqvarna",
        modelo: "Norden 901",
        estilo: "Enduro",
        anio: 2022,
        condicion: "Usada",
        cilindrada: 901,
        cilindradaMedida: "cc",
        potencia: 105,
        kilometraje: 5000,
        precio: 15990,
        rating: 1,
        imagen: "/product/img_norden_901.jpeg",
        logo: "/logo/logo_husqvarna.png"
    },
    {
        id: 17,
        marca: "Husqvarna",
        modelo: "Enduro 701",
        estilo: "Enduro",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 701,
        cilindradaMedida: "cc",
        potencia: 75,
        kilometraje: 0,
        precio: 10990,
        rating: 4,
        imagen: "/product/img_enduro_701.webp",
        logo: "/logo/logo_husqvarna.png"
    },
    {
        id: 18,
        marca: "Husqvarna",
        modelo: "Viptilen 401",
        estilo: "Street",
        anio: 2018,
        condicion: "Usada",
        cilindrada: 401,
        cilindradaMedida: "cc",
        potencia: 45,
        kilometraje: 8500,
        precio: 6900,
        rating: 4,
        imagen: "/product/img_viptilen_401.avif",
        logo: "/logo/logo_husqvarna.png"
    },
    {
        id: 19,
        marca: "Yamaha",
        modelo: "XSR900",
        estilo: "Street",
        anio: 2020,
        condicion: "Usada",
        cilindrada: 900,
        cilindradaMedida: "cc",
        potencia: 115,
        kilometraje: 500,
        precio: 20900,
        rating: 5,
        imagen: "/product/img_xsr900.avif",
        logo: "/logo/logo_yamaha.png"
    },
    {
        id: 20,
        marca: "Yamaha",
        modelo: "Jog",
        estilo: "Scooter",
        anio: 1990,
        condicion: "Usada",
        cilindrada: 45,
        cilindradaMedida: "cc",
        potencia: 4.5,
        kilometraje: 25000,
        precio: 1090,
        rating: 5,
        imagen: "/product/img_jog.webp",
        logo: "/logo/logo_yamaha.png"
    },
    {
        id: 22,
        marca: "Harley Davidson",
        modelo: "Tri Glide Ultra",
        estilo: "Cruiser",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 114,
        cilindradaMedida: "ci",
        potencia: 90,
        kilometraje: 0,
        precio: 59900,
        rating: 2,
        imagen: "/product/img_tri_glide_ultra.webp",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 23,
        marca: "Ducati",
        modelo: "Panigale V4",
        estilo: "Sport",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 1100,
        cilindradaMedida: "cc",
        potencia: 210,
        kilometraje: 0,
        precio: 49900,
        rating: 4,
        imagen: "/product/img_panigale_v4.webp",
        logo: "/logo/logo_ducati.png"
    },
    {
        id: 24,
        marca: "Ducati",
        modelo: "DesertX",
        estilo: "Enduro",
        anio: 2022,
        condicion: "Usada",
        cilindrada: 937,
        cilindradaMedida: "cc",
        potencia: 110,
        kilometraje: 10000,
        precio: 27900,
        rating: 4,
        imagen: "/product/img_desertx.webp",
        logo: "/logo/logo_ducati.png"
    },
    {
        id: 25,
        marca: "Ducati",
        modelo: "XDiavel",
        estilo: "Street",
        anio: 2018,
        condicion: "Usada",
        cilindrada: 1262,
        cilindradaMedida: "cc",
        potencia: 150,
        kilometraje: 25000,
        precio: 25900,
        rating: 5,
        imagen: "/product/img_xdiavel.png",
        logo: "/logo/logo_ducati.png"
    },
    {
        id: 26,
        marca: "Harley Davidson",
        modelo: "Fat Boy",
        estilo: "Cruiser",
        anio: 2003,
        condicion: "Usada",
        cilindrada: 1450,
        cilindradaMedida: "cc",
        potencia: 65,
        kilometraje: 55000,
        precio: 20900,
        rating: 5,
        imagen: "/product/img_fat_boy.jpeg",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 27,
        marca: "Harley Davidson",
        modelo: "Pan America",
        estilo: "Enduro",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 1250,
        cilindradaMedida: "cc",
        potencia: 150,
        kilometraje: 0,
        precio: 32900,
        rating: 5,
        imagen: "/product/img_pan_america.png",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 28,
        marca: "BMW",
        modelo: "R 1200 GS Adventure",
        estilo: "Enduro",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 1200,
        cilindradaMedida: "cc",
        potencia: 125,
        kilometraje: 0,
        precio: 49900,
        rating: 5,
        imagen: "/product/img_r1200_gs_adventure.jpeg",
        logo: "/logo/logo_bmw.png"
    },
    {
        id: 29,
        marca: "BMW",
        modelo: "S1000 RR",
        estilo: "Sport",
        anio: 2020,
        condicion: "Usada",
        cilindrada: 1000,
        cilindradaMedida: "cc",
        potencia: 205,
        kilometraje: 15000,
        precio: 29900,
        rating: 1,
        imagen: "/product/img_s1000_rr.avif",
        logo: "/logo/logo_bmw.png"
    },
    {
        id: 30,
        marca: "BMW",
        modelo: "CE 04",
        estilo: "Scooter",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 0,
        cilindradaMedida: "-",
        potencia: 20,
        kilometraje: 0,
        precio: 19900,
        rating: 3,
        imagen: "/product/img_ce_04.webp",
        logo: "/logo/logo_bmw.png"
    },
    {
        id: 31,
        marca: "Husqvarna",
        modelo: "FC 450",
        estilo: "Cross",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 450,
        cilindradaMedida: "cc",
        potencia: 60,
        kilometraje: 0,
        precio: 17900,
        rating: 5,
        imagen: "/product/img_fc_450.png",
        logo: "/logo/logo_husqvarna.png"
    },
    {
        id: 32,
        marca: "Husqvarna",
        modelo: "Vitpilen 701",
        estilo: "Street",
        anio: 2018,
        condicion: "Usada",
        cilindrada: 692,
        cilindradaMedida: "cc",
        potencia: 75,
        kilometraje: 15000,
        precio: 12900,
        rating: 4,
        imagen: "/product/img_vitpilen_701.jpeg",
        logo: "/logo/logo_husqvarna.png"
    },
    {
        id: 33,
        marca: "Kawasaki",
        modelo: "Z900 RS",
        estilo: "Street",
        anio: 2020,
        condicion: "Usada",
        cilindrada: 900,
        cilindradaMedida: "cc",
        potencia: 110,
        kilometraje: 12500,
        precio: 18900,
        rating: 4,
        imagen: "/product/img_z900_rs.png",
        logo: "/logo/logo_kawasaki.svg"
    },
    {
        id: 34,
        marca: "Kawasaki",
        modelo: "KX450",
        estilo: "Cross",
        anio: 2022,
        condicion: "Usada",
        cilindrada: 450,
        cilindradaMedida: "cc",
        potencia: 55,
        kilometraje: 1500,
        precio: 12900,
        rating: 3,
        imagen: "/product/img_kx450.png",
        logo: "/logo/logo_kawasaki.svg"
    },
    {
        id: 35,
        marca: "Kawasaki",
        modelo: "ZX6-R",
        estilo: "Sport",
        anio: 2010,
        condicion: "Usada",
        cilindrada: 600,
        cilindradaMedida: "cc",
        potencia: 130,
        kilometraje: 1500,
        precio: 10900,
        rating: 2,
        imagen: "/product/img_zx6r.jpeg",
        logo: "/logo/logo_kawasaki.svg"
    },
    {
        id: 36,
        marca: "KTM",
        modelo: "1290 Super Adventure R",
        estilo: "Enduro",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 1290,
        cilindradaMedida: "cc",
        potencia: 160,
        kilometraje: 0,
        precio: 40900,
        rating: 5,
        imagen: "/product/img_1290_super_adventure_r.jpeg",
        logo: "/logo/logo_ktm.png"
    },
    {
        id: 37,
        marca: "KTM",
        modelo: "1290 Super Duke R",
        estilo: "Street",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 1290,
        cilindradaMedida: "cc",
        potencia: 180,
        kilometraje: 0,
        precio: 30900,
        rating: 5,
        imagen: "/product/img_1290_super_duke_r.png",
        logo: "/logo/logo_ktm.png"
    },
    {
        id: 38,
        marca: "Indian",
        modelo: "Challenger Elite",
        estilo: "Cruiser",
        anio: 2022,
        condicion: "Nueva",
        cilindrada: 108,
        cilindradaMedida: "ci",
        potencia: 120,
        kilometraje: 0,
        precio: 50900,
        rating: 2,
        imagen: "/product/img_challenger_elite.png",
        logo: "/logo/logo_indian.svg"
    },
    {
        id: 39,
        marca: "Indian",
        modelo: "FTR Rally",
        estilo: "Street",
        anio: 2022,
        condicion: "Nueva",
        cilindrada: 75,
        cilindradaMedida: "ci",
        potencia: 120,
        kilometraje: 0,
        precio: 35900,
        rating: 3,
        imagen: "/product/img_ftr_rally.jpeg",
        logo: "/logo/logo_indian.svg"
    },
    {
        id: 40,
        marca: "Triumph",
        modelo: "Rocket 3 GT",
        estilo: "Street",
        anio: 2022,
        condicion: "Usada",
        cilindrada: 2500,
        cilindradaMedida: "cc",
        potencia: 165,
        kilometraje: 16500,
        precio: 35900,
        rating: 3,
        imagen: "/product/img_rocket_3_gt.png",
        logo: "/logo/logo_triumph.svg"
    },
    {
        id: 41,
        marca: "Triumph",
        modelo: "Tiger 1200 Rally Pro",
        estilo: "Enduro",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 1200,
        cilindradaMedida: "cc",
        potencia: 105,
        kilometraje: 0,
        precio: 29900,
        rating: 4,
        imagen: "/product/img_tiger_1200_rally_pro.avif",
        logo: "/logo/logo_triumph.svg"
    },
    {
        id: 42,
        marca: "Triumph",
        modelo: "Thruxton RS",
        estilo: "Street",
        anio: 2020,
        condicion: "Usada",
        cilindrada: 1200,
        cilindradaMedida: "cc",
        potencia: 100,
        kilometraje: 900,
        precio: 29900,
        rating: 4,
        imagen: "/product/img_thruxton_rs.avif",
        logo: "/logo/logo_triumph.svg"
    },
    {
        id: 43,
        marca: "Ducati",
        modelo: "Monster 1100 EVO",
        estilo: "Street",
        anio: 2020,
        condicion: "Usada",
        cilindrada: 1100,
        cilindradaMedida: "cc",
        potencia: 100,
        kilometraje: 40000,
        precio: 12900,
        rating: 5,
        imagen: "/product/img_monster_1100_evo.webp",
        logo: "/logo/logo_ducati.png"
    },
    {
        id: 44,
        marca: "Indian",
        modelo: "Scout Bobber",
        estilo: "Cruiser",
        anio: 2020,
        condicion: "Usada",
        cilindrada: 70,
        cilindradaMedida: "ci",
        potencia: 100,
        kilometraje: 8000,
        precio: 22900,
        rating: 4,
        imagen: "/product/img_scout.jpeg",
        logo: "/logo/logo_indian.svg"
    },
    {
        id: 45,
        marca: "KTM",
        modelo: "125 SX",
        estilo: "Cross",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 125,
        cilindradaMedida: "cc",
        potencia: 30,
        kilometraje: 0,
        precio: 10900,
        rating: 4,
        imagen: "/product/img_sx_125.png",
        logo: "/logo/logo_ktm.png"
    },
    {
        id: 46,
        marca: "KTM",
        modelo: "RC 200",
        estilo: "Sport",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 200,
        cilindradaMedida: "cc",
        potencia: 25,
        kilometraje: 0,
        precio: 6900,
        rating: 2,
        imagen: "/product/img_rc_200.png",
        logo: "/logo/logo_ktm.png"
    },
    {
        id: 47,
        marca: "Triumph",
        modelo: "Bonneville T120",
        estilo: "Street",
        anio: 2019,
        condicion: "Usada",
        cilindrada: 1200,
        cilindradaMedida: "cc",
        potencia: 80,
        kilometraje: 8500,
        precio: 26900,
        rating: 3,
        imagen: "/product/img_bonneville_t120.webp",
        logo: "/logo/logo_triumph.svg"
    },
    {
        id: 48,
        marca: "Harley Davidson",
        modelo: "Road King Classic",
        estilo: "Cruiser",
        anio: 2015,
        condicion: "Usada",
        cilindrada: 103,
        cilindradaMedida: "ci",
        potencia: 72,
        kilometraje: 50000,
        precio: 34900,
        rating: 1,
        imagen: "/product/img_road_king_classic.jpeg",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 49,
        marca: "Harley Davidson",
        modelo: "Sportster Seventy Two",
        estilo: "Cruiser",
        anio: 2018,
        condicion: "Usada",
        cilindrada: 1200,
        cilindradaMedida: "cc",
        potencia: 55,
        kilometraje: 7500,
        precio: 20900,
        rating: 2,
        imagen: "/product/img_sportster_seventy_two.jpeg",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 50,
        marca: "Honda",
        modelo: "CRF 1000 Africa Twin",
        estilo: "Enduro",
        anio: 2020,
        condicion: "Usada",
        cilindrada: 1000,
        cilindradaMedida: "cc",
        potencia: 100,
        kilometraje: 7500,
        precio: 26900,
        rating: 1,
        imagen: "/product/img_crf1000_africa_twin.jpeg",
        logo: "/logo/logo_honda.svg"
    },
    {
        id: 51,
        marca: "Honda",
        modelo: "CRF450",
        estilo: "Cross",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 450,
        cilindradaMedida: "cc",
        potencia: 52.5,
        kilometraje: 0,
        precio: 16900,
        rating: 3,
        imagen: "/product/img_crf450.webp",
        logo: "/logo/logo_honda.svg"
    },
    {
        id: 52,
        marca: "Honda",
        modelo: "CB650R",
        estilo: "Street",
        anio: 2022,
        condicion: "Usada",
        cilindrada: 650,
        cilindradaMedida: "cc",
        potencia: 80,
        kilometraje: 5500,
        precio: 17900,
        rating: 5,
        imagen: "/product/img_cb650r.avif",
        logo: "/logo/logo_honda.svg"
    },
    {
        id: 53,
        marca: "Honda",
        modelo: "CBX750",
        estilo: "Street",
        anio: 1990,
        condicion: "Usada",
        cilindrada: 750,
        cilindradaMedida: "cc",
        potencia: 95,
        kilometraje: 50000,
        precio: 7500,
        rating: 4,
        imagen: "/product/img_cbx750.webp",
        logo: "/logo/logo_honda.svg"
    },
    {
        id: 54,
        marca: "Honda",
        modelo: "CBR1000RR",
        estilo: "Sport",
        anio: 2020,
        condicion: "Nueva",
        cilindrada: 1000,
        cilindradaMedida: "cc",
        potencia: 215,
        kilometraje: 0,
        precio: 26900,
        rating: 4,
        imagen: "/product/img_cbr1000rr.avif",
        logo: "/logo/logo_honda.svg"
    },
    {
        id: 55,
        marca: "Harley Davidson",
        modelo: "Street Glide CVO",
        estilo: "Cruiser",
        anio: 2020,
        condicion: "Nueva",
        cilindrada: 117,
        cilindradaMedida: "ci",
        potencia: 115,
        kilometraje: 0,
        precio: 68900,
        rating: 2,
        imagen: "/product/img_cvo_street_glide.png",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 56,
        marca: "Harley Davidson",
        modelo: "Sportster 883 Iron",
        estilo: "Street",
        anio: 2015,
        condicion: "Usada",
        cilindrada: 883,
        cilindradaMedida: "cc",
        potencia: 65,
        kilometraje: 42500,
        precio: 14900,
        rating: 2,
        imagen: "/product/img_sportster_iron_883.jpeg",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 57,
        marca: "Harley Davidson",
        modelo: "Electra Glide Ultra Classic",
        estilo: "Cruiser",
        anio: 2018,
        condicion: "Usada",
        cilindrada: 107,
        cilindradaMedida: "ci",
        potencia: 85,
        kilometraje: 20500,
        precio: 34900,
        rating: 2,
        imagen: "/product/img_ultra_classic.png",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 58,
        marca: "Harley Davidson",
        modelo: "Sportster XL1200R Roadster",
        estilo: "Street",
        anio: 2016,
        condicion: "Usada",
        cilindrada: 1200,
        cilindradaMedida: "cc",
        potencia: 75,
        kilometraje: 25000,
        precio: 18900,
        rating: 5,
        imagen: "/product/img_xl1200_sportster_roadster.jpeg",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 59,
        marca: "Honda",
        modelo: "Gold Wing",
        estilo: "Cruiser",
        anio: 2018,
        condicion: "Usada",
        cilindrada: 1800,
        cilindradaMedida: "cc",
        potencia: 125,
        kilometraje: 5000,
        precio: 26900,
        rating: 2,
        imagen: "/product/img_gold_wing.avif",
        logo: "/logo/logo_honda.svg"
    },
    {
        id: 60,
        marca: "BMW",
        modelo: "R NineT",
        estilo: "Street",
        anio: 2024,
        condicion: "Nueva",
        cilindrada: 1200,
        cilindradaMedida: "cc",
        potencia: 115,
        kilometraje: 0,
        precio: 34900,
        rating: 4,
        imagen: "/product/img_r_ninet.avif",
        logo: "/logo/logo_bmw.png"
    },
    {
        id: 61,
        marca: "Harley Davidson",
        modelo: "Softail Street Bob",
        estilo: "Street",
        anio: 2018,
        condicion: "Usada",
        cilindrada: 107,
        cilindradaMedida: "ci",
        potencia: 75,
        kilometraje: 0,
        precio: 22900,
        rating: 3,
        imagen: "/product/img_softail_street_bob.png",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 62,
        marca: "Harley Davidson",
        modelo: "Dyna Fat Bob",
        estilo: "Street",
        anio: 2015,
        condicion: "Usada",
        cilindrada: 103,
        cilindradaMedida: "ci",
        potencia: 75,
        kilometraje: 0,
        precio: 20900,
        rating: 4,
        imagen: "/product/img_dyna_fat_bob.jpeg",
        logo: "/logo/logo_harley_davidson.svg"
    },
    {
        id: 63,
        marca: "Harley Davidson",
        modelo: "Softail Heritage Classic",
        estilo: "Cruiser",
        anio: 2015,
        condicion: "Usada",
        cilindrada: 103,
        cilindradaMedida: "ci",
        potencia: 75,
        kilometraje: 0,
        precio: 21900,
        rating: 3,
        imagen: "/product/img_softail_heritage_classic.jpeg",
        logo: "/logo/logo_harley_davidson.svg"
    }
]

function getProducts() {
    return new Promise( (resolve, reject) => {
        setTimeout( () => {
            resolve(products)
        }, 1000)
    })
}

export default getProducts;